// Single source of truth for all REST API endpoints
// Drives the playground forms, docs tables, and OpenAPI generation

export type ParamLocation = "query" | "body";

export interface ApiParam {
  name: string;
  type: "string" | "number" | "boolean" | "object" | "array";
  required: boolean;
  location: ParamLocation;
  description: string;
  enumValues?: string[];
  default?: string;
  nested?: ApiParam[];
}

export interface ApiEndpoint {
  id: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  category: string;
  title: string;
  description: string;
  params: ApiParam[];
  responseExample: Record<string, unknown>;
}

export const API_CATEGORIES = [
  "Leads",
  "Contatos",
  "Conversas",
  "Handoffs",
  "Pipeline",
  "Atividades",
  "Tarefas",
  "Arquivos",
  "Dashboard",
  "Fontes",
  "Auditoria",
  "Campanhas",
  "Grupos",
] as const;

export type ApiCategory = (typeof API_CATEGORIES)[number];

export const ALL_ENDPOINTS: ApiEndpoint[] = [
  // ---- Leads ----
  {
    id: "inbound-lead",
    method: "POST",
    path: "/api/v1/inbound/lead",
    category: "Leads",
    title: "Criar Lead (Inbound)",
    description: "Cria um lead com contato e mensagem opcionais. Auto-atribui a agente IA se configurado.",
    params: [
      { name: "title", type: "string", required: true, location: "body", description: "Título do lead" },
      { name: "contact", type: "object", required: false, location: "body", description: "Dados do contato", nested: [
        { name: "email", type: "string", required: false, location: "body", description: "Email do contato" },
        { name: "phone", type: "string", required: false, location: "body", description: "Telefone" },
        { name: "firstName", type: "string", required: false, location: "body", description: "Primeiro nome" },
        { name: "lastName", type: "string", required: false, location: "body", description: "Sobrenome" },
        { name: "company", type: "string", required: false, location: "body", description: "Empresa" },
      ]},
      { name: "message", type: "string", required: false, location: "body", description: "Mensagem inicial (cria conversa)" },
      { name: "channel", type: "string", required: false, location: "body", description: "Canal da conversa", enumValues: ["whatsapp", "telegram", "email", "webchat", "internal"], default: "webchat" },
      { name: "value", type: "number", required: false, location: "body", description: "Valor do lead", default: "0" },
      { name: "currency", type: "string", required: false, location: "body", description: "Moeda (ex: BRL)" },
      { name: "priority", type: "string", required: false, location: "body", description: "Prioridade", enumValues: ["low", "medium", "high", "urgent"], default: "medium" },
      { name: "temperature", type: "string", required: false, location: "body", description: "Temperatura", enumValues: ["cold", "warm", "hot"], default: "cold" },
      { name: "sourceId", type: "string", required: false, location: "body", description: "ID da fonte do lead" },
      { name: "tags", type: "array", required: false, location: "body", description: "Tags do lead", default: "[]" },
      { name: "customFields", type: "object", required: false, location: "body", description: "Campos personalizados", default: "{}" },
    ],
    responseExample: { success: true, leadId: "jd7x8k2m9n4p5q1r", contactId: "k3b7y9w2x5z8a4c6" },
  },
  {
    id: "list-leads",
    method: "GET",
    path: "/api/v1/leads",
    category: "Leads",
    title: "Listar Leads",
    description: "Lista leads com filtros opcionais por board, etapa e responsável.",
    params: [
      { name: "boardId", type: "string", required: false, location: "query", description: "Filtrar por board" },
      { name: "stageId", type: "string", required: false, location: "query", description: "Filtrar por etapa" },
      { name: "assignedTo", type: "string", required: false, location: "query", description: "Filtrar por responsável" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      leads: [
        { _id: "jd7x8k2m9n4p5q1r", title: "Novo lead via formulário", boardId: "kn8y...", stageId: "m2a4...", contactId: "p5b7...", assignedTo: null, value: 5000, priority: "medium", temperature: "warm", tags: [], customFields: {}, _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|jd7x8k2m9n4p5q1r",
      hasMore: false,
    },
  },
  {
    id: "get-lead",
    method: "GET",
    path: "/api/v1/leads/get",
    category: "Leads",
    title: "Detalhes do Lead",
    description: "Retorna detalhes completos de um lead por ID.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID do lead" },
    ],
    responseExample: {
      lead: { _id: "jd7x8k2m9n4p5q1r", title: "Lead exemplo", boardId: "kn8y...", stageId: "m2a4...", contactId: "p5b7...", assignedTo: null, value: 5000, priority: "medium", temperature: "warm", tags: ["inbound"], customFields: {}, _creationTime: 1739620800000 },
    },
  },
  {
    id: "update-lead",
    method: "POST",
    path: "/api/v1/leads/update",
    category: "Leads",
    title: "Atualizar Lead",
    description: "Atualiza campos de um lead existente.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
      { name: "title", type: "string", required: false, location: "body", description: "Novo título" },
      { name: "value", type: "number", required: false, location: "body", description: "Novo valor" },
      { name: "priority", type: "string", required: false, location: "body", description: "Nova prioridade", enumValues: ["low", "medium", "high", "urgent"] },
      { name: "temperature", type: "string", required: false, location: "body", description: "Nova temperatura", enumValues: ["cold", "warm", "hot"] },
      { name: "tags", type: "array", required: false, location: "body", description: "Novas tags" },
      { name: "customFields", type: "object", required: false, location: "body", description: "Campos personalizados" },
      { name: "sourceId", type: "string", required: false, location: "body", description: "ID da fonte" },
    ],
    responseExample: { success: true },
  },
  {
    id: "delete-lead",
    method: "POST",
    path: "/api/v1/leads/delete",
    category: "Leads",
    title: "Remover Lead",
    description: "Remove permanentemente um lead.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
    ],
    responseExample: { success: true },
  },
  {
    id: "move-lead-stage",
    method: "POST",
    path: "/api/v1/leads/move-stage",
    category: "Leads",
    title: "Mover Lead de Etapa",
    description: "Move um lead para outra etapa do pipeline.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
      { name: "stageId", type: "string", required: true, location: "body", description: "ID da nova etapa" },
    ],
    responseExample: { success: true },
  },
  {
    id: "assign-lead",
    method: "POST",
    path: "/api/v1/leads/assign",
    category: "Leads",
    title: "Atribuir Lead",
    description: "Atribui um lead a um membro da equipe.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
      { name: "assignedTo", type: "string", required: false, location: "body", description: "ID do membro (null para desatribuir)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "request-handoff",
    method: "POST",
    path: "/api/v1/leads/handoff",
    category: "Leads",
    title: "Solicitar Repasse",
    description: "Solicita repasse de IA para humano em um lead.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
      { name: "reason", type: "string", required: true, location: "body", description: "Motivo do repasse" },
      { name: "toMemberId", type: "string", required: false, location: "body", description: "ID do membro destino" },
      { name: "summary", type: "string", required: false, location: "body", description: "Resumo do contexto" },
      { name: "suggestedActions", type: "array", required: false, location: "body", description: "Ações sugeridas", default: "[]" },
    ],
    responseExample: { success: true, handoffId: "h4n8d0f2f9i3d1x7" },
  },

  // ---- Contacts ----
  {
    id: "list-contacts",
    method: "GET",
    path: "/api/v1/contacts",
    category: "Contatos",
    title: "Listar Contatos",
    description: "Lista todos os contatos da organização.",
    params: [
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "500" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      contacts: [
        { _id: "k3b7y9w2x5z8a4c6", firstName: "Maria", lastName: "Silva", email: "maria@empresa.com", phone: "+5511999999999", company: "Empresa LTDA", _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|k3b7y9w2x5z8a4c6",
      hasMore: false,
    },
  },
  {
    id: "create-contact",
    method: "POST",
    path: "/api/v1/contacts/create",
    category: "Contatos",
    title: "Criar Contato",
    description: "Cria um novo contato na organização.",
    params: [
      { name: "firstName", type: "string", required: false, location: "body", description: "Primeiro nome" },
      { name: "lastName", type: "string", required: false, location: "body", description: "Sobrenome" },
      { name: "email", type: "string", required: false, location: "body", description: "Email" },
      { name: "phone", type: "string", required: false, location: "body", description: "Telefone" },
      { name: "company", type: "string", required: false, location: "body", description: "Empresa" },
      { name: "title", type: "string", required: false, location: "body", description: "Cargo" },
      { name: "whatsappNumber", type: "string", required: false, location: "body", description: "Número WhatsApp" },
      { name: "telegramUsername", type: "string", required: false, location: "body", description: "Username Telegram" },
      { name: "tags", type: "array", required: false, location: "body", description: "Tags" },
      { name: "bio", type: "string", required: false, location: "body", description: "Bio" },
      { name: "linkedinUrl", type: "string", required: false, location: "body", description: "URL LinkedIn" },
      { name: "city", type: "string", required: false, location: "body", description: "Cidade" },
      { name: "state", type: "string", required: false, location: "body", description: "Estado" },
      { name: "country", type: "string", required: false, location: "body", description: "País" },
      { name: "industry", type: "string", required: false, location: "body", description: "Setor" },
      { name: "companySize", type: "string", required: false, location: "body", description: "Porte da empresa" },
      { name: "cnpj", type: "string", required: false, location: "body", description: "CNPJ" },
      { name: "companyWebsite", type: "string", required: false, location: "body", description: "Website" },
      { name: "customFields", type: "object", required: false, location: "body", description: "Campos personalizados" },
    ],
    responseExample: { success: true, contactId: "k3b7y9w2x5z8a4c6" },
  },
  {
    id: "get-contact",
    method: "GET",
    path: "/api/v1/contacts/get",
    category: "Contatos",
    title: "Detalhes do Contato",
    description: "Retorna detalhes completos de um contato por ID.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID do contato" },
    ],
    responseExample: {
      contact: { _id: "k3b7y9w2x5z8a4c6", firstName: "Maria", lastName: "Silva", email: "maria@empresa.com", phone: "+5511999999999", company: "Empresa LTDA", tags: ["cliente"], _creationTime: 1739620800000 },
    },
  },
  {
    id: "update-contact",
    method: "POST",
    path: "/api/v1/contacts/update",
    category: "Contatos",
    title: "Atualizar Contato",
    description: "Atualiza dados de um contato existente.",
    params: [
      { name: "contactId", type: "string", required: true, location: "body", description: "ID do contato" },
      { name: "firstName", type: "string", required: false, location: "body", description: "Primeiro nome" },
      { name: "lastName", type: "string", required: false, location: "body", description: "Sobrenome" },
      { name: "email", type: "string", required: false, location: "body", description: "Email" },
      { name: "phone", type: "string", required: false, location: "body", description: "Telefone" },
      { name: "company", type: "string", required: false, location: "body", description: "Empresa" },
      { name: "title", type: "string", required: false, location: "body", description: "Cargo" },
      { name: "tags", type: "array", required: false, location: "body", description: "Tags" },
      { name: "city", type: "string", required: false, location: "body", description: "Cidade" },
      { name: "state", type: "string", required: false, location: "body", description: "Estado" },
      { name: "country", type: "string", required: false, location: "body", description: "País" },
      { name: "customFields", type: "object", required: false, location: "body", description: "Campos personalizados" },
    ],
    responseExample: { success: true },
  },
  {
    id: "enrich-contact",
    method: "POST",
    path: "/api/v1/contacts/enrich",
    category: "Contatos",
    title: "Enriquecer Contato",
    description: "Enriquece dados do contato via agente de IA.",
    params: [
      { name: "contactId", type: "string", required: true, location: "body", description: "ID do contato" },
      { name: "fields", type: "object", required: true, location: "body", description: "Campos a enriquecer (chave: valor)" },
      { name: "source", type: "string", required: true, location: "body", description: "Fonte dos dados (ex: linkedin, google)" },
      { name: "confidence", type: "number", required: false, location: "body", description: "Confiança (0-1)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "contact-gaps",
    method: "GET",
    path: "/api/v1/contacts/gaps",
    category: "Contatos",
    title: "Gaps de Enriquecimento",
    description: "Retorna campos vazios do contato que podem ser enriquecidos.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID do contato" },
    ],
    responseExample: {
      contact: { _id: "k3b7y9w2x5z8a4c6", firstName: "Maria", missingFields: ["linkedinUrl", "industry", "companySize"], enrichmentScore: 45 },
    },
  },
  {
    id: "search-contacts",
    method: "GET",
    path: "/api/v1/contacts/search",
    category: "Contatos",
    title: "Buscar Contatos",
    description: "Busca contatos por texto (nome, email, empresa).",
    params: [
      { name: "q", type: "string", required: true, location: "query", description: "Texto de busca" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 100)", default: "20" },
    ],
    responseExample: {
      contacts: [
        { _id: "k3b7y9w2x5z8a4c6", firstName: "Maria", lastName: "Silva", email: "maria@empresa.com", company: "Empresa LTDA" },
      ],
    },
  },

  // ---- Conversations ----
  {
    id: "list-conversations",
    method: "GET",
    path: "/api/v1/conversations",
    category: "Conversas",
    title: "Listar Conversas",
    description: "Lista conversas, opcionalmente filtradas por lead. Por padrão só conversas 1 a 1 — salas de grupo só com kind=group ou kind=all.",
    params: [
      { name: "leadId", type: "string", required: false, location: "query", description: "Filtrar por lead" },
      { name: "kind", type: "string", required: false, location: "query", description: "direct (padrão) | group | all — sala de grupo não tem lead nem contato", default: "direct" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      conversations: [
        { _id: "c9v2s4t7n1a8e3r6", leadId: "jd7x8k2m9n4p5q1r", channel: "webchat", status: "active", lastMessageAt: 1739620800000, _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|c9v2s4t7n1a8e3r6",
      hasMore: false,
    },
  },
  {
    id: "get-messages",
    method: "GET",
    path: "/api/v1/conversations/messages",
    category: "Conversas",
    title: "Mensagens da Conversa",
    description: "Retorna todas as mensagens de uma conversa.",
    params: [
      { name: "conversationId", type: "string", required: true, location: "query", description: "ID da conversa" },
    ],
    responseExample: {
      messages: [
        { _id: "m5s8g3j1k7p4q9w2", conversationId: "c9v2s4t7n1a8e3r6", content: "Olá, gostaria de saber mais.", contentType: "text", isInternal: false, _creationTime: 1739620800000 },
      ],
    },
  },
  {
    id: "send-message",
    method: "POST",
    path: "/api/v1/conversations/send",
    category: "Conversas",
    title: "Enviar Mensagem",
    description: "Envia uma mensagem em uma conversa existente. Aceita anexos (IDs de arquivos da org) e resposta/quote a outra mensagem.",
    params: [
      { name: "conversationId", type: "string", required: true, location: "body", description: "ID da conversa" },
      { name: "content", type: "string", required: false, location: "body", description: "Conteúdo da mensagem (obrigatório sem attachments)" },
      { name: "contentType", type: "string", required: false, location: "body", description: "Tipo de conteúdo", enumValues: ["text", "image", "file", "audio"], default: "text" },
      { name: "isInternal", type: "boolean", required: false, location: "body", description: "Nota interna?", default: "false" },
      { name: "attachments", type: "array", required: false, location: "body", description: "IDs de arquivos (tabela files) a anexar" },
      { name: "replyToMessageId", type: "string", required: false, location: "body", description: "ID da mensagem sendo respondida (quote)" },
    ],
    responseExample: { success: true, messageId: "m5s8g3j1k7p4q9w2" },
  },
  {
    id: "receive-message",
    method: "POST",
    path: "/api/v1/conversations/receive",
    category: "Conversas",
    title: "Receber Mensagem (Inbound)",
    description: "Injeta uma mensagem inbound de um contato — para bridges externas de qualquer canal. Cria contato e lead se não existirem; idempotente por externalId.",
    params: [
      { name: "content", type: "string", required: true, location: "body", description: "Conteúdo da mensagem" },
      { name: "contactPhone", type: "string", required: false, location: "body", description: "Telefone do contato (obrigatório sem contactId; cria o contato se não existir)" },
      { name: "contactId", type: "string", required: false, location: "body", description: "ID de um contato existente (alternativa a contactPhone)" },
      { name: "channel", type: "string", required: false, location: "body", description: "Canal da conversa", enumValues: ["whatsapp", "telegram", "email", "webchat"], default: "whatsapp" },
      { name: "contentType", type: "string", required: false, location: "body", description: "Tipo de conteúdo", enumValues: ["text", "image", "file", "audio"], default: "text" },
      { name: "contactFirstName", type: "string", required: false, location: "body", description: "Nome (usado ao criar contato novo)" },
      { name: "contactLastName", type: "string", required: false, location: "body", description: "Sobrenome (usado ao criar contato novo)" },
      { name: "leadTitle", type: "string", required: false, location: "body", description: "Título do lead criado quando o contato não tem lead" },
      { name: "externalId", type: "string", required: false, location: "body", description: "ID externo da mensagem (dedupe em reentregas)" },
    ],
    responseExample: { success: true, messageId: "m5s8g3j1k7p4q9w2", leadId: "jd7x8k2m9n4p5q1r", contactId: "k2m9n4p5q1rjd7x8" },
  },

  // ---- Handoffs ----
  {
    id: "list-handoffs",
    method: "GET",
    path: "/api/v1/handoffs",
    category: "Handoffs",
    title: "Listar Handoffs",
    description: "Lista handoffs com filtro opcional por status.",
    params: [
      { name: "status", type: "string", required: false, location: "query", description: "Filtrar por status", enumValues: ["pending", "accepted", "rejected"] },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      handoffs: [
        { _id: "h4n8d0f2f9i3d1x7", leadId: "jd7x8k2m9n4p5q1r", status: "pending", reason: "Cliente pediu atendimento humano", _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|h4n8d0f2f9i3d1x7",
      hasMore: false,
    },
  },
  {
    id: "pending-handoffs",
    method: "GET",
    path: "/api/v1/handoffs/pending",
    category: "Handoffs",
    title: "Handoffs Pendentes",
    description: "Lista apenas handoffs com status pendente.",
    params: [],
    responseExample: {
      handoffs: [
        { _id: "h4n8d0f2f9i3d1x7", leadId: "jd7x8k2m9n4p5q1r", status: "pending", reason: "Negociação complexa", _creationTime: 1739620800000 },
      ],
    },
  },
  {
    id: "accept-handoff",
    method: "POST",
    path: "/api/v1/handoffs/accept",
    category: "Handoffs",
    title: "Aceitar Handoff",
    description: "Aceita um handoff pendente.",
    params: [
      { name: "handoffId", type: "string", required: true, location: "body", description: "ID do handoff" },
      { name: "notes", type: "string", required: false, location: "body", description: "Notas de aceitação" },
    ],
    responseExample: { success: true },
  },
  {
    id: "reject-handoff",
    method: "POST",
    path: "/api/v1/handoffs/reject",
    category: "Handoffs",
    title: "Rejeitar Handoff",
    description: "Rejeita um handoff pendente.",
    params: [
      { name: "handoffId", type: "string", required: true, location: "body", description: "ID do handoff" },
      { name: "notes", type: "string", required: false, location: "body", description: "Motivo da rejeição" },
    ],
    responseExample: { success: true },
  },

  // ---- Pipeline / Reference ----
  {
    id: "list-boards",
    method: "GET",
    path: "/api/v1/boards",
    category: "Pipeline",
    title: "Listar Boards",
    description: "Lista boards (pipelines) com suas etapas.",
    params: [],
    responseExample: {
      boards: [
        {
          _id: "kn8y3b7w2x5z8a4c",
          name: "Pipeline Vendas",
          isDefault: true,
          stages: [
            { _id: "m2a4...", name: "Novo", order: 0 },
            { _id: "n5b8...", name: "Qualificado", order: 1 },
            { _id: "p7c2...", name: "Proposta", order: 2 },
            { _id: "q9d4...", name: "Fechado", order: 3 },
          ],
        },
      ],
    },
  },
  {
    id: "list-team-members",
    method: "GET",
    path: "/api/v1/team-members",
    category: "Pipeline",
    title: "Listar Membros da Equipe",
    description: "Lista todos os membros da equipe (humanos e IA).",
    params: [],
    responseExample: {
      members: [
        { _id: "t2m5k8j3n7p1q4w9", name: "Ana Costa", type: "human", role: "admin", status: "active" },
        { _id: "t3m6k9j4n8p2q5w0", name: "Agente IA", type: "ai", role: "member", status: "active" },
      ],
    },
  },
  {
    id: "list-field-definitions",
    method: "GET",
    path: "/api/v1/field-definitions",
    category: "Pipeline",
    title: "Listar Campos Personalizados",
    description: "Lista definições de campos personalizados.",
    params: [],
    responseExample: {
      fields: [
        { _id: "f1d3k5j7n9p1q3w5", name: "receita_anual", label: "Receita Anual", type: "number", entityType: "lead" },
      ],
    },
  },

  // ---- Activities ----
  {
    id: "list-activities",
    method: "GET",
    path: "/api/v1/activities",
    category: "Atividades",
    title: "Listar Atividades",
    description: "Lista atividades de um lead.",
    params: [
      { name: "leadId", type: "string", required: true, location: "query", description: "ID do lead" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 200)", default: "50" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      activities: [
        { _id: "a1c3t5v7y9b1d3f5", leadId: "jd7x8k2m9n4p5q1r", type: "note", content: "Ligação realizada", _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|a1c3t5v7y9b1d3f5",
      hasMore: false,
    },
  },
  {
    id: "create-activity",
    method: "POST",
    path: "/api/v1/activities",
    category: "Atividades",
    title: "Criar Atividade",
    description: "Cria uma atividade em um lead.",
    params: [
      { name: "leadId", type: "string", required: true, location: "body", description: "ID do lead" },
      { name: "type", type: "string", required: true, location: "body", description: "Tipo da atividade", enumValues: ["note", "call", "email", "meeting", "task"] },
      { name: "content", type: "string", required: false, location: "body", description: "Conteúdo da atividade" },
      { name: "metadata", type: "object", required: false, location: "body", description: "Metadados adicionais" },
    ],
    responseExample: { success: true, activityId: "a1c3t5v7y9b1d3f5" },
  },

  // ---- Tarefas ----
  {
    id: "list-tasks",
    method: "GET",
    path: "/api/v1/tasks",
    category: "Tarefas",
    title: "Listar Tarefas",
    description: "Lista tarefas com filtros opcionais por status, prioridade, responsável, lead e tipo.",
    params: [
      { name: "status", type: "string", required: false, location: "query", description: "Filtrar por status", enumValues: ["pending", "in_progress", "completed", "cancelled"] },
      { name: "priority", type: "string", required: false, location: "query", description: "Filtrar por prioridade", enumValues: ["low", "medium", "high", "urgent"] },
      { name: "assignedTo", type: "string", required: false, location: "query", description: "Filtrar por responsável" },
      { name: "leadId", type: "string", required: false, location: "query", description: "Filtrar por lead" },
      { name: "contactId", type: "string", required: false, location: "query", description: "Filtrar por contato" },
      { name: "type", type: "string", required: false, location: "query", description: "Filtrar por tipo", enumValues: ["task", "reminder"] },
      { name: "activityType", type: "string", required: false, location: "query", description: "Filtrar por tipo de atividade", enumValues: ["todo", "call", "email", "follow_up", "meeting", "research"] },
      { name: "dueBefore", type: "number", required: false, location: "query", description: "Data limite antes de (timestamp ms)" },
      { name: "dueAfter", type: "number", required: false, location: "query", description: "Data limite após (timestamp ms)" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      tasks: [
        { _id: "tk1a2b3c4d5e6f7g", title: "Ligar para cliente", type: "task", status: "pending", priority: "high", activityType: "call", dueDate: 1739620800000, assignedTo: "t2m5k8j3n7p1q4w9", leadId: "jd7x8k2m9n4p5q1r", _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|tk1a2b3c4d5e6f7g",
      hasMore: false,
    },
  },
  {
    id: "get-task",
    method: "GET",
    path: "/api/v1/tasks/get",
    category: "Tarefas",
    title: "Detalhes da Tarefa",
    description: "Retorna detalhes completos de uma tarefa por ID.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID da tarefa" },
    ],
    responseExample: {
      task: { _id: "tk1a2b3c4d5e6f7g", title: "Ligar para cliente", type: "task", status: "pending", priority: "high", activityType: "call", dueDate: 1739620800000, assignedTo: "t2m5k8j3n7p1q4w9", leadId: "jd7x8k2m9n4p5q1r", checklist: [{ id: "c1", title: "Preparar pauta", completed: true }], _creationTime: 1739620800000 },
    },
  },
  {
    id: "my-tasks",
    method: "GET",
    path: "/api/v1/tasks/my",
    category: "Tarefas",
    title: "Minhas Tarefas",
    description: "Retorna tarefas pendentes e em andamento do agente autenticado.",
    params: [],
    responseExample: {
      tasks: [
        { _id: "tk1a2b3c4d5e6f7g", title: "Follow-up com lead", type: "task", status: "pending", priority: "medium", activityType: "follow_up", dueDate: 1739620800000, _creationTime: 1739620800000 },
      ],
    },
  },
  {
    id: "overdue-tasks",
    method: "GET",
    path: "/api/v1/tasks/overdue",
    category: "Tarefas",
    title: "Tarefas Atrasadas",
    description: "Lista tarefas com data de vencimento no passado e status pendente ou em andamento.",
    params: [
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      tasks: [
        { _id: "tk1a2b3c4d5e6f7g", title: "Enviar proposta", type: "task", status: "pending", priority: "urgent", dueDate: 1739534400000, _creationTime: 1739448000000 },
      ],
      nextCursor: "1739534400000|tk1a2b3c4d5e6f7g",
      hasMore: false,
    },
  },
  {
    id: "search-tasks",
    method: "GET",
    path: "/api/v1/tasks/search",
    category: "Tarefas",
    title: "Buscar Tarefas",
    description: "Busca tarefas por texto (título, descrição).",
    params: [
      { name: "q", type: "string", required: true, location: "query", description: "Texto de busca" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 100)", default: "50" },
    ],
    responseExample: {
      tasks: [
        { _id: "tk1a2b3c4d5e6f7g", title: "Pesquisar concorrentes", type: "task", status: "in_progress", priority: "medium", activityType: "research", _creationTime: 1739620800000 },
      ],
    },
  },
  {
    id: "create-task",
    method: "POST",
    path: "/api/v1/tasks/create",
    category: "Tarefas",
    title: "Criar Tarefa",
    description: "Cria uma nova tarefa ou lembrete.",
    params: [
      { name: "title", type: "string", required: true, location: "body", description: "Título da tarefa" },
      { name: "type", type: "string", required: false, location: "body", description: "Tipo", enumValues: ["task", "reminder"], default: "task" },
      { name: "priority", type: "string", required: false, location: "body", description: "Prioridade", enumValues: ["low", "medium", "high", "urgent"], default: "medium" },
      { name: "activityType", type: "string", required: false, location: "body", description: "Tipo de atividade CRM", enumValues: ["todo", "call", "email", "follow_up", "meeting", "research"] },
      { name: "description", type: "string", required: false, location: "body", description: "Descrição detalhada" },
      { name: "dueDate", type: "number", required: false, location: "body", description: "Data de vencimento (timestamp ms)" },
      { name: "leadId", type: "string", required: false, location: "body", description: "ID do lead associado" },
      { name: "contactId", type: "string", required: false, location: "body", description: "ID do contato associado" },
      { name: "assignedTo", type: "string", required: false, location: "body", description: "ID do membro responsável" },
      { name: "recurrence", type: "object", required: false, location: "body", description: "Recorrência", nested: [
        { name: "pattern", type: "string", required: true, location: "body", description: "Padrão", enumValues: ["daily", "weekly", "biweekly", "monthly"] },
        { name: "endDate", type: "number", required: false, location: "body", description: "Data final (timestamp ms)" },
      ]},
      { name: "checklist", type: "array", required: false, location: "body", description: "Itens do checklist" },
      { name: "tags", type: "array", required: false, location: "body", description: "Tags" },
    ],
    responseExample: { success: true, taskId: "tk1a2b3c4d5e6f7g" },
  },
  {
    id: "update-task",
    method: "POST",
    path: "/api/v1/tasks/update",
    category: "Tarefas",
    title: "Atualizar Tarefa",
    description: "Atualiza campos de uma tarefa existente.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
      { name: "title", type: "string", required: false, location: "body", description: "Novo título" },
      { name: "description", type: "string", required: false, location: "body", description: "Nova descrição" },
      { name: "priority", type: "string", required: false, location: "body", description: "Nova prioridade", enumValues: ["low", "medium", "high", "urgent"] },
      { name: "activityType", type: "string", required: false, location: "body", description: "Novo tipo de atividade", enumValues: ["todo", "call", "email", "follow_up", "meeting", "research"] },
      { name: "dueDate", type: "number", required: false, location: "body", description: "Nova data de vencimento (timestamp ms)" },
      { name: "tags", type: "array", required: false, location: "body", description: "Novas tags" },
    ],
    responseExample: { success: true },
  },
  {
    id: "complete-task",
    method: "POST",
    path: "/api/v1/tasks/complete",
    category: "Tarefas",
    title: "Concluir Tarefa",
    description: "Marca uma tarefa como concluída.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
    ],
    responseExample: { success: true },
  },
  {
    id: "delete-task",
    method: "POST",
    path: "/api/v1/tasks/delete",
    category: "Tarefas",
    title: "Remover Tarefa",
    description: "Remove permanentemente uma tarefa.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
    ],
    responseExample: { success: true },
  },
  {
    id: "assign-task",
    method: "POST",
    path: "/api/v1/tasks/assign",
    category: "Tarefas",
    title: "Atribuir Tarefa",
    description: "Atribui ou desatribui uma tarefa a um membro da equipe.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
      { name: "assignedTo", type: "string", required: false, location: "body", description: "ID do membro (omita para desatribuir)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "snooze-task",
    method: "POST",
    path: "/api/v1/tasks/snooze",
    category: "Tarefas",
    title: "Definir Lembrete",
    description: "Define um lembrete para uma tarefa.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
      { name: "snoozedUntil", type: "number", required: true, location: "body", description: "Data/hora do lembrete (timestamp ms)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "bulk-tasks",
    method: "POST",
    path: "/api/v1/tasks/bulk",
    category: "Tarefas",
    title: "Operações em Lote",
    description: "Executa operações em lote em múltiplas tarefas (completar, deletar, atribuir).",
    params: [
      { name: "taskIds", type: "array", required: true, location: "body", description: "IDs das tarefas" },
      { name: "action", type: "string", required: true, location: "body", description: "Ação a executar", enumValues: ["complete", "delete", "assign"] },
      { name: "assignedTo", type: "string", required: false, location: "body", description: "ID do membro (apenas para ação assign)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "list-task-comments",
    method: "GET",
    path: "/api/v1/tasks/comments",
    category: "Tarefas",
    title: "Listar Comentários",
    description: "Lista comentários de uma tarefa.",
    params: [
      { name: "taskId", type: "string", required: true, location: "query", description: "ID da tarefa" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 500)", default: "200" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
    ],
    responseExample: {
      comments: [
        { _id: "tc1a2b3c4d5e6f7g", taskId: "tk1a2b3c4d5e6f7g", authorId: "t2m5k8j3n7p1q4w9", authorType: "human", content: "Ligação feita, cliente pediu retorno quinta.", _creationTime: 1739620800000 },
      ],
      nextCursor: "1739620800000|tc1a2b3c4d5e6f7g",
      hasMore: false,
    },
  },
  {
    id: "add-task-comment",
    method: "POST",
    path: "/api/v1/tasks/comments/add",
    category: "Tarefas",
    title: "Adicionar Comentário",
    description: "Adiciona um comentário a uma tarefa.",
    params: [
      { name: "taskId", type: "string", required: true, location: "body", description: "ID da tarefa" },
      { name: "content", type: "string", required: true, location: "body", description: "Conteúdo do comentário" },
      { name: "mentionedUserIds", type: "array", required: false, location: "body", description: "IDs de membros mencionados" },
    ],
    responseExample: { success: true, commentId: "tc1a2b3c4d5e6f7g" },
  },

  // ---- Files ----
  {
    id: "generate-upload-url",
    method: "POST",
    path: "/api/v1/files/upload-url",
    category: "Arquivos",
    title: "Gerar URL de Upload",
    description: "Gera uma URL presigned para upload direto de arquivo ao Convex Storage.",
    params: [],
    responseExample: { uploadUrl: "https://convex-storage.s3.amazonaws.com/..." },
  },
  {
    id: "save-file",
    method: "POST",
    path: "/api/v1/files",
    category: "Arquivos",
    title: "Salvar Metadados de Arquivo",
    description: "Salva metadados do arquivo após upload. Valida tipo MIME, tamanho e cotas.",
    params: [
      { name: "storageId", type: "string", required: true, location: "body", description: "ID de storage retornado pelo upload" },
      { name: "name", type: "string", required: true, location: "body", description: "Nome do arquivo" },
      { name: "mimeType", type: "string", required: true, location: "body", description: "Tipo MIME (ex: image/jpeg, application/pdf)" },
      { name: "size", type: "number", required: true, location: "body", description: "Tamanho em bytes" },
      { name: "fileType", type: "string", required: true, location: "body", description: "Tipo de arquivo", enumValues: ["message_attachment", "contact_photo", "member_avatar", "lead_document", "import_file", "other"] },
      { name: "messageId", type: "string", required: false, location: "body", description: "ID da mensagem (para anexos)" },
      { name: "contactId", type: "string", required: false, location: "body", description: "ID do contato (para fotos)" },
      { name: "leadId", type: "string", required: false, location: "body", description: "ID do lead (para documentos)" },
      { name: "metadata", type: "object", required: false, location: "body", description: "Metadados adicionais" },
    ],
    responseExample: { success: true, fileId: "f1l3s2t4r5a6g7e8" },
  },
  {
    id: "get-file-url",
    method: "GET",
    path: "/api/v1/files/:id/url",
    category: "Arquivos",
    title: "Obter URL de Download",
    description: "Retorna URL de download para um arquivo. URL expira após alguns minutos.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID do arquivo" },
    ],
    responseExample: { url: "https://convex-storage.s3.amazonaws.com/download/..." },
  },
  {
    id: "delete-file",
    method: "DELETE",
    path: "/api/v1/files/:id",
    category: "Arquivos",
    title: "Remover Arquivo",
    description: "Remove arquivo e seus metadados permanentemente do storage.",
    params: [
      { name: "id", type: "string", required: true, location: "query", description: "ID do arquivo" },
    ],
    responseExample: { success: true },
  },

  // ---- Dashboard ----
  {
    id: "dashboard",
    method: "GET",
    path: "/api/v1/dashboard",
    category: "Dashboard",
    title: "Dashboard Analytics",
    description: "Retorna métricas e KPIs do dashboard.",
    params: [],
    responseExample: {
      totalLeads: 142,
      leadsThisMonth: 28,
      conversionRate: 0.23,
      totalValue: 450000,
      leadsByStage: { Novo: 45, Qualificado: 32, Proposta: 18, Fechado: 12 },
      tasks: { total: 24, byStatus: { pending: 10, in_progress: 5, completed: 8, cancelled: 1 } },
    },
  },

  // ---- Lead Sources ----
  {
    id: "list-lead-sources",
    method: "GET",
    path: "/api/v1/lead-sources",
    category: "Fontes",
    title: "Listar Fontes de Lead",
    description: "Lista todas as fontes de leads configuradas.",
    params: [],
    responseExample: {
      sources: [
        { _id: "s1r3c5e7g9i1k3m5", name: "Website", type: "organic", isActive: true },
        { _id: "s2r4c6e8g0i2k4m6", name: "Google Ads", type: "paid", isActive: true },
      ],
    },
  },

  // ---- Audit Logs ----
  {
    id: "list-audit-logs",
    method: "GET",
    path: "/api/v1/audit-logs",
    category: "Auditoria",
    title: "Listar Logs de Auditoria",
    description: "Lista logs de auditoria com filtros avançados e paginação por cursor.",
    params: [
      { name: "entityType", type: "string", required: false, location: "query", description: "Tipo de entidade" },
      { name: "action", type: "string", required: false, location: "query", description: "Tipo de ação", enumValues: ["create", "update", "delete", "stage_change", "assign", "handoff_request", "handoff_accept", "handoff_reject"] },
      { name: "severity", type: "string", required: false, location: "query", description: "Severidade", enumValues: ["low", "medium", "high", "critical"] },
      { name: "actorId", type: "string", required: false, location: "query", description: "ID do ator" },
      { name: "startDate", type: "number", required: false, location: "query", description: "Data início (timestamp ms)" },
      { name: "endDate", type: "number", required: false, location: "query", description: "Data fim (timestamp ms)" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor para paginação" },
      { name: "limit", type: "number", required: false, location: "query", description: "Limite de resultados (max 200)" },
    ],
    responseExample: {
      logs: [
        { _id: "al1g3k5m7o9q1s3u", entityType: "lead", action: "create", severity: "low", description: "Lead criado: Novo lead", _creationTime: 1739620800000 },
      ],
      nextCursor: "eyJ...",
      hasMore: true,
    },
  },
  // ---- Campanhas de WhatsApp ----
  {
    id: "list-campaigns",
    method: "GET",
    path: "/api/v1/campaigns",
    category: "Campanhas",
    title: "Listar Campanhas",
    description: "Lista campanhas de WhatsApp (disparo em massa) com status, canal e contadores.",
    params: [
      { name: "status", type: "string", required: false, location: "query", description: "Filtrar por status", enumValues: ["draft", "scheduled", "running", "paused", "completed", "canceled", "failed"] },
    ],
    responseExample: {
      campaigns: [
        { _id: "c4mp41gn0001", name: "Promo setembro", status: "running", provider: "bridge", contentKind: "text", channel: { displayName: "Bridge", provider: "bridge" }, stats: { total: 120, pending: 80, sent: 30, delivered: 8, read: 1, replied: 1, failed: 0, skipped: 0, optedOut: 0 } },
      ],
    },
  },
  {
    id: "get-campaign",
    method: "GET",
    path: "/api/v1/campaigns/get",
    category: "Campanhas",
    title: "Obter Campanha",
    description: "Detalhes de uma campanha: conteúdo, público, agenda, limites, segurança, stats e timeline.",
    params: [{ name: "campaignId", type: "string", required: true, location: "query", description: "ID da campanha" }],
    responseExample: { campaign: { _id: "c4mp41gn0001", name: "Promo setembro", status: "draft", provider: "bridge", safeMode: true, pacing: { minDelaySec: 30, maxDelaySec: 90, maxPerDay: 120 } } },
  },
  {
    id: "campaign-report",
    method: "GET",
    path: "/api/v1/campaigns/report",
    category: "Campanhas",
    title: "Relatório da Campanha",
    description: "Contadores, taxas (entrega/leitura/resposta/falha/opt-out), motivos de falha, custo estimado e progresso.",
    params: [{ name: "campaignId", type: "string", required: true, location: "query", description: "ID da campanha" }],
    responseExample: { report: { stats: { total: 120, sent: 100 }, rates: { delivered: 92.5, read: 61, replied: 12.3, failed: 3.1, optedOut: 0.8 }, progress: 83.3 } },
  },
  {
    id: "campaign-recipients",
    method: "GET",
    path: "/api/v1/campaigns/recipients",
    category: "Campanhas",
    title: "Destinatários da Campanha",
    description: "Lista paginada de destinatários com status por linha (pending, queued, sent, delivered, read, replied, failed, skipped, opted_out).",
    params: [
      { name: "campaignId", type: "string", required: true, location: "query", description: "ID da campanha" },
      { name: "status", type: "string", required: false, location: "query", description: "Filtrar por status" },
      { name: "search", type: "string", required: false, location: "query", description: "Telefone ou nome" },
      { name: "limit", type: "number", required: false, location: "query", description: "Máx. 500", default: "100" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor de paginação" },
    ],
    responseExample: { recipients: [{ phone: "5511999990000", status: "delivered", sentAt: 1757356800000 }], nextCursor: null, hasMore: false },
  },
  {
    id: "campaign-safe-defaults",
    method: "GET",
    path: "/api/v1/campaigns/safe-defaults",
    category: "Campanhas",
    title: "Limites Seguros do Canal",
    description: "Defaults seguros de envio para o canal (por idade do número no bridge / tier na Meta) e o teto duro.",
    params: [
      { name: "channelConfigId", type: "string", required: true, location: "query", description: "ID do canal WhatsApp" },
      { name: "tier", type: "string", required: false, location: "query", description: "Tier Meta (ex.: TIER_250)" },
      { name: "audienceSource", type: "string", required: false, location: "query", description: "groups devolve a tabela de limites das salas (20/dia, 8/h, ≥60 s)" },
    ],
    responseExample: { defaults: { provider: "bridge", warmupDay: 10, safe: { minDelaySec: 30, maxDelaySec: 90, maxPerHour: 30, maxPerDay: 120 }, hardCap: { maxPerDay: 200 } } },
  },
  {
    id: "campaign-preview-audience",
    method: "POST",
    path: "/api/v1/campaigns/preview-audience",
    category: "Campanhas",
    title: "Prever Público",
    description: "Conta e amostra quem a campanha alcançaria (sem criar nada): leads do CRM, as salas de grupos monitorados ou os membros dessas salas.",
    params: [
      { name: "source", type: "string", required: false, location: "body", description: "segment (padrão), groups (a sala é o destinatário) ou group_members (privado, 1 a 1)" },
      { name: "filters", type: "object", required: true, location: "body", description: "Filtros do segmento (boardId, stageIds, tags, temperature, priority, lastActivityBefore/After, onlyOpenWindow, excludeCampaignedWithinDays)" },
      { name: "groupChatIds", type: "array", required: false, location: "body", description: "Grupos monitorados do mesmo canal (groups / group_members)" },
      { name: "memberFilters", type: "object", required: false, location: "body", description: "{ excludeAdmins, excludeExistingContacts, excludeCampaignedWithinDays, activeInGroupWithinDays, excludeGroupChatIds, includeKeys }" },
      { name: "channelConfigId", type: "string", required: false, location: "body", description: "Canal da campanha (valida que os grupos são do mesmo número)" },
    ],
    responseExample: { preview: { count: 42, sample: [{ name: "Maria", phone: "5511••••0000", group: "Clientes SP" }], excluded: { no_phone: 3, opted_out: 1 }, funnel: { total: 60, withPhone: 52, deduped: 48, afterOptOut: 47, final: 42 }, estimatedDays: 5 } },
  },
  {
    id: "create-campaign",
    method: "POST",
    path: "/api/v1/campaigns/create",
    category: "Campanhas",
    title: "Criar Campanha (rascunho)",
    description: "Cria um rascunho. Lançar exige aceites humanos (consentimento LGPD; risco do bridge).",
    params: [
      { name: "name", type: "string", required: true, location: "body", description: "Nome" },
      { name: "channelConfigId", type: "string", required: true, location: "body", description: "Canal WhatsApp (Meta ou bridge)" },
      { name: "content", type: "object", required: true, location: "body", description: "{ kind: text|template, variants: [{ text }], template?: { name, language, bodyParams } }" },
      { name: "audience", type: "object", required: false, location: "body", description: "{ source: segment|manual|import|groups|group_members, filters?, groupChatIds?, memberFilters?, targetBoardId?, targetStageId? }", default: "{ source: manual }" },
      { name: "schedule", type: "object", required: false, location: "body", description: "Janela de envio (fuso, horas, dias)" },
      { name: "pacing", type: "object", required: false, location: "body", description: "Limites (omita para os defaults seguros)" },
      { name: "safety", type: "object", required: false, location: "body", description: "checkNumbersFirst, allowLinks, kill switches" },
    ],
    responseExample: { success: true, campaignId: "c4mp41gn0001" },
  },
  {
    id: "update-campaign",
    method: "POST",
    path: "/api/v1/campaigns/update",
    category: "Campanhas",
    title: "Atualizar Campanha",
    description: "Edita um rascunho (tudo) ou uma campanha pausada (só limites, agenda e segurança).",
    params: [
      { name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" },
      { name: "patch", type: "object", required: true, location: "body", description: "Campos a alterar" },
    ],
    responseExample: { success: true },
  },
  {
    id: "campaign-add-recipients",
    method: "POST",
    path: "/api/v1/campaigns/recipients",
    category: "Campanhas",
    title: "Adicionar Destinatários",
    description: "Números manuais (entries ≤500) ou CSV (csv ≤5 MB / fileId + mapping; dryRun valida sem gravar).",
    params: [
      { name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha (rascunho)" },
      { name: "entries", type: "array", required: false, location: "body", description: "[{ phone, name?, vars? }]" },
      { name: "csv", type: "string", required: false, location: "body", description: "Texto CSV com cabeçalho" },
      { name: "mapping", type: "object", required: false, location: "body", description: "{ phone, name?, email?, company?, varsColumns? }" },
      { name: "dryRun", type: "boolean", required: false, location: "body", description: "Só validar" },
    ],
    responseExample: { success: true, added: 118, invalid: [], duplicates: 2, suppressed: 0 },
  },
  {
    id: "launch-campaign",
    method: "POST",
    path: "/api/v1/campaigns/launch",
    category: "Campanhas",
    title: "Lançar Campanha",
    description: "Lança um rascunho. Exige consentAck (LGPD) e, no bridge, bridgeRiskAck (+ newNumberRiskAck se o número tem menos de 3 dias — aviso, não trava); acima do modo seguro, overrideAck + overrideWord=ENTENDO.",
    params: [
      { name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" },
      { name: "consentAck", type: "boolean", required: true, location: "body", description: "Tenho consentimento/base legal para contatar a lista" },
      { name: "bridgeRiskAck", type: "boolean", required: false, location: "body", description: "Aceito o risco de banimento (bridge)" },
      { name: "newNumberRiskAck", type: "boolean", required: false, location: "body", description: "Aceito disparar por número bridge recém-conectado (< 3 dias; exigido quando safe-defaults devolve newNumberRisk)" },
      { name: "groupMembersDmAck", type: "boolean", required: false, location: "body", description: "Exigido no público group_members: mensagem privada a quem não iniciou conversa" },
      { name: "overrideAck", type: "boolean", required: false, location: "body", description: "Lançar acima do modo seguro" },
      { name: "overrideWord", type: "string", required: false, location: "body", description: "ENTENDO" },
      { name: "tierAtLaunch", type: "string", required: false, location: "body", description: "Tier Meta lido antes (GET /whatsapp/tier)" },
    ],
    responseExample: { success: true, status: "running", warnings: [], estimatedCostUsd: 0 },
  },
  {
    id: "pause-campaign",
    method: "POST",
    path: "/api/v1/campaigns/pause",
    category: "Campanhas",
    title: "Pausar Campanha",
    description: "Pausa os envios (pode retomar depois).",
    params: [
      { name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" },
      { name: "reason", type: "string", required: false, location: "body", description: "Motivo" },
    ],
    responseExample: { success: true },
  },
  {
    id: "resume-campaign",
    method: "POST",
    path: "/api/v1/campaigns/resume",
    category: "Campanhas",
    title: "Retomar Campanha",
    description: "Retoma uma campanha pausada.",
    params: [{ name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" }],
    responseExample: { success: true },
  },
  {
    id: "cancel-campaign",
    method: "POST",
    path: "/api/v1/campaigns/cancel",
    category: "Campanhas",
    title: "Cancelar Campanha",
    description: "Cancela (pendentes viram skipped). Não pode ser desfeito.",
    params: [{ name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" }],
    responseExample: { success: true },
  },
  {
    id: "retry-failed-campaign",
    method: "POST",
    path: "/api/v1/campaigns/retry-failed",
    category: "Campanhas",
    title: "Reenviar Falhas",
    description: "Reenfileira falhas elegíveis (131049 vencido, falhas de rede, cancelados) de campanha pausada/concluída.",
    params: [{ name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" }],
    responseExample: { success: true, requeued: 4 },
  },
  {
    id: "delete-campaign",
    method: "POST",
    path: "/api/v1/campaigns/delete",
    category: "Campanhas",
    title: "Excluir Campanha",
    description: "Exclui rascunho/cancelada/concluída (cascata de destinatários).",
    params: [{ name: "campaignId", type: "string", required: true, location: "body", description: "ID da campanha" }],
    responseExample: { success: true },
  },
  {
    id: "list-opt-outs",
    method: "GET",
    path: "/api/v1/opt-outs",
    category: "Campanhas",
    title: "Lista de Supressão",
    description: "Números que nunca recebem campanha (palavra-chave inbound, erro 131050 da Meta, manual).",
    params: [
      { name: "search", type: "string", required: false, location: "query", description: "Dígitos do telefone" },
      { name: "limit", type: "number", required: false, location: "query", description: "Máx. 500", default: "100" },
      { name: "cursor", type: "string", required: false, location: "query", description: "Cursor" },
    ],
    responseExample: { optOuts: [{ _id: "0pt0ut0001", phone: "5511999990000", source: "keyword", createdAt: 1757356800000 }], nextCursor: null, hasMore: false },
  },
  {
    id: "add-opt-out",
    method: "POST",
    path: "/api/v1/opt-outs",
    category: "Campanhas",
    title: "Adicionar à Supressão",
    description: "Marca um telefone (ou o telefone de um contato) como \"não contatar\".",
    params: [
      { name: "phone", type: "string", required: false, location: "body", description: "Telefone" },
      { name: "contactId", type: "string", required: false, location: "body", description: "Contato (usa o telefone dele)" },
      { name: "reason", type: "string", required: false, location: "body", description: "Motivo" },
    ],
    responseExample: { success: true, optOutId: "0pt0ut0001" },
  },
  {
    id: "remove-opt-out",
    method: "DELETE",
    path: "/api/v1/opt-outs",
    category: "Campanhas",
    title: "Remover da Supressão",
    description: "Remove uma entrada da lista de supressão (campaigns:full, auditado como high).",
    params: [{ name: "optOutId", type: "string", required: true, location: "query", description: "ID da entrada" }],
    responseExample: { success: true },
  },
  {
    id: "list-whatsapp-templates",
    method: "GET",
    path: "/api/v1/whatsapp/templates",
    category: "Campanhas",
    title: "Templates Meta",
    description: "Templates da Cloud API em cache para o canal (status, categoria, qualidade, corpo, botões).",
    params: [
      { name: "channelConfigId", type: "string", required: true, location: "query", description: "Canal Meta" },
      { name: "onlyApproved", type: "boolean", required: false, location: "query", description: "Só aprovados" },
    ],
    responseExample: { templates: [{ name: "promo_setembro", language: "pt_BR", category: "MARKETING", status: "APPROVED", qualityScore: "GREEN", bodyParamCount: 1 }] },
  },
  {
    id: "sync-whatsapp-templates",
    method: "POST",
    path: "/api/v1/whatsapp/templates/sync",
    category: "Campanhas",
    title: "Sincronizar Templates",
    description: "Baixa os templates da Meta para o cache do canal.",
    params: [{ name: "channelConfigId", type: "string", required: true, location: "body", description: "Canal Meta" }],
    responseExample: { success: true, synced: 7, removed: 0, approved: 5 },
  },
  {
    id: "whatsapp-tier",
    method: "GET",
    path: "/api/v1/whatsapp/tier",
    category: "Campanhas",
    title: "Tier do Portfólio Meta",
    description: "Limite de envio do portfólio (whatsapp_business_manager_messaging_limit), ex.: TIER_250.",
    params: [{ name: "channelConfigId", type: "string", required: true, location: "query", description: "Canal Meta" }],
    responseExample: { tier: "TIER_250", limit: 250 },
  },
  // ---- Grupos de WhatsApp (canal bridge) ----
  {
    id: "list-groups",
    method: "GET",
    path: "/api/v1/groups",
    category: "Grupos",
    title: "Listar Grupos",
    description: "Grupos conhecidos pelos números bridge da organização. Acompanhar é opt-in POR grupo: um grupo listado não é necessariamente ingerido. Não devolve a lista de participantes.",
    params: [
      { name: "channelConfigId", type: "string", required: false, location: "query", description: "Só os grupos deste número" },
      { name: "includeRemoved", type: "boolean", required: false, location: "query", description: "Inclui grupos dos quais o número saiu" },
    ],
    responseExample: {
      groups: [
        { _id: "gr0up0001", jid: "120363111@g.us", subject: "Clientes SP", monitored: true, participantsCount: 42, weAreAdmin: false, lastMessageAt: 1757356800000 },
      ],
    },
  },
  {
    id: "get-group",
    method: "GET",
    path: "/api/v1/groups/get",
    category: "Grupos",
    title: "Obter Grupo",
    description: "Um grupo com a lista de participantes (nome do PushName, telefone, LID, admin, contato vinculado quando o telefone já é contato) e a política de IA da sala. Grupo NÃO acompanhado devolve participants vazio — o dado dos membros é de terceiros e só fica guardado enquanto a sala é de fato acompanhada.",
    params: [{ name: "groupChatId", type: "string", required: true, location: "query", description: "ID do grupo" }],
    responseExample: {
      group: {
        _id: "gr0up0001",
        subject: "Clientes SP",
        jid: "120363111@g.us",
        monitored: true,
        participants: [{ lid: "111@lid", phone: "5511999990001", name: "Maria", isAdmin: false, isSuperAdmin: false, contactId: "c0nt4ct0001", isSelf: false }],
        selfKey: "92965187932215@lid",
        selfKnown: true,
      },
    },
  },
  {
    id: "group-messages",
    method: "GET",
    path: "/api/v1/groups/messages",
    category: "Grupos",
    title: "Mensagens do Grupo",
    description: "Mensagens da sala, das mais recentes para as mais antigas. O autor de uma mensagem recebida é um MEMBRO (o nome vem do PushName), não um membro da equipe.",
    params: [
      { name: "groupChatId", type: "string", required: true, location: "query", description: "ID do grupo" },
      { name: "limit", type: "number", required: false, location: "query", description: "Máx. 200", default: "50" },
    ],
    responseExample: {
      messages: [
        { _id: "m3ss4g30001", direction: "inbound", content: "alguém tem o link?", senderName: "Maria", senderPhone: "5511999990001", senderLid: "111@lid", mentions: [], createdAt: 1757356800000 },
      ],
    },
  },
  {
    id: "send-group-message",
    method: "POST",
    path: "/api/v1/groups/send",
    category: "Grupos",
    title: "Enviar no Grupo",
    description: "Manda uma mensagem num grupo acompanhado. O \"@fulano\" no texto é escolha de quem escreve; mentions é o que faz o WhatsApp destacar e notificar. Mesmo caminho de envio do 1:1 (pacing, webhook, dispatch).",
    params: [
      { name: "groupChatId", type: "string", required: true, location: "body", description: "ID do grupo (precisa estar acompanhado)" },
      { name: "content", type: "string", required: true, location: "body", description: "Texto da mensagem (ou envie attachments)" },
      { name: "mentions", type: "array", required: false, location: "body", description: "JIDs dos membros mencionados (LID ou telefone), vindos de /groups/get" },
      { name: "replyToMessageId", type: "string", required: false, location: "body", description: "Cita esta mensagem na sala" },
      { name: "attachments", type: "array", required: false, location: "body", description: "IDs de arquivos já enviados por /files" },
    ],
    responseExample: { success: true, messageId: "m3ss4g30002", conversationId: "c0nv3rs0001" },
  },
  {
    id: "group-monitor",
    method: "POST",
    path: "/api/v1/groups/monitor",
    category: "Grupos",
    title: "Acompanhar Grupo",
    description: "Passa a acompanhar (ou para de acompanhar) um grupo. Ligar cria a conversa no inbox; desligar ARQUIVA a conversa — o histórico já ingerido nunca é apagado. Exige settings:manage.",
    params: [
      { name: "groupChatId", type: "string", required: true, location: "body", description: "ID do grupo" },
      { name: "monitored", type: "boolean", required: true, location: "body", description: "true acompanha, false para de acompanhar" },
    ],
    responseExample: { success: true, groupChatId: "gr0up0001", monitored: true },
  },
  {
    id: "group-sync",
    method: "POST",
    path: "/api/v1/groups/sync",
    category: "Grupos",
    title: "Sincronizar Grupos",
    description: "Atualiza a lista de grupos do número a partir do gateway (nome, admins, participantes). NUNCA liga nem desliga o acompanhamento. Exige settings:manage.",
    params: [{ name: "channelConfigId", type: "string", required: true, location: "body", description: "Canal bridge" }],
    responseExample: { success: true, upserted: 3, removed: 0, detail: "3 grupo(s) sincronizado(s)" },
  },
  {
    id: "list-group-posts",
    method: "GET",
    path: "/api/v1/group-posts",
    category: "Grupos",
    title: "Listar Publicações Programadas",
    description: "Publicações programadas em grupos (\"todo dia às 12h o assistente posta no grupo X\"): status, agenda em palavras, salas de destino, próximo envio e contadores.",
    params: [
      { name: "status", type: "string", required: false, location: "query", description: "Filtrar por status", enumValues: ["draft", "active", "paused", "ended"] },
      { name: "channelConfigId", type: "string", required: false, location: "query", description: "Só as publicações deste número" },
    ],
    responseExample: {
      posts: [
        { _id: "p0st0001", name: "Bom dia", status: "active", scheduleText: "Todos os dias às 12:00", targetNames: ["Clientes SP"], nextRunAt: 1757376000000, stats: { sent: 12, skipped: 1, failed: 0 } },
      ],
    },
  },
  {
    id: "get-group-post",
    method: "GET",
    path: "/api/v1/group-posts/get",
    category: "Grupos",
    title: "Obter Publicação",
    description: "Destinos enriquecidos, agenda, conteúdo (biblioteca ou IA), stats e o texto que estiver aguardando aprovação.",
    params: [{ name: "groupPostId", type: "string", required: true, location: "query", description: "ID da publicação" }],
    responseExample: { post: { _id: "p0st0001", name: "Bom dia", status: "draft", scheduleText: "Todos os dias às 12:00", targets: [{ groupChatId: "gr0up0001", subject: "Clientes SP", monitored: true, left: false }] } },
  },
  {
    id: "create-group-post",
    method: "POST",
    path: "/api/v1/group-posts/create",
    category: "Grupos",
    title: "Criar Publicação (rascunho)",
    description: "Cria um rascunho. Nasce sempre em draft: ativar é decisão à parte (campaigns:full), porque a partir dali o CRM escreve sozinho numa sala de gente real.",
    params: [
      { name: "name", type: "string", required: true, location: "body", description: "Nome da rotina" },
      { name: "groupChatIds", type: "array", required: true, location: "body", description: "Grupos acompanhados, todos do MESMO número" },
      { name: "schedule", type: "object", required: true, location: "body", description: "{ timezone, times: [\"12:00\"], days?: [1..7], startAt?, endAt?, jitterMinutes? }" },
      { name: "content", type: "object", required: true, location: "body", description: "{ kind: library, library: { items: [{ text }], order } } ou { kind: ai, ai: { prompt, requiresApproval } }" },
    ],
    responseExample: { success: true, groupPostId: "p0st0001" },
  },
  {
    id: "update-group-post",
    method: "POST",
    path: "/api/v1/group-posts/update",
    category: "Grupos",
    title: "Editar Publicação",
    description: "Edita nome, destinos, agenda ou conteúdo. Publicação ativa é reagendada na hora; trocar o conteúdo invalida o texto pendente de aprovação.",
    params: [
      { name: "groupPostId", type: "string", required: true, location: "body", description: "ID da publicação" },
      { name: "name", type: "string", required: false, location: "body", description: "Novo nome" },
      { name: "groupChatIds", type: "array", required: false, location: "body", description: "Novos destinos" },
      { name: "schedule", type: "object", required: false, location: "body", description: "Nova agenda" },
      { name: "content", type: "object", required: false, location: "body", description: "Novo conteúdo" },
    ],
    responseExample: { success: true },
  },
  {
    id: "activate-group-post",
    method: "POST",
    path: "/api/v1/group-posts/activate",
    category: "Grupos",
    title: "Ativar Publicação",
    description: "Liga a publicação: o CRM passa a postar sozinho nos grupos, na agenda configurada. Re-valida todos os destinos e audita como high. Exige campaigns:full.",
    params: [{ name: "groupPostId", type: "string", required: true, location: "body", description: "ID da publicação" }],
    responseExample: { success: true },
  },
  {
    id: "pause-group-post",
    method: "POST",
    path: "/api/v1/group-posts/pause",
    category: "Grupos",
    title: "Pausar Publicação",
    description: "Para os envios imediatamente; a publicação pode ser ativada de novo depois.",
    params: [
      { name: "groupPostId", type: "string", required: true, location: "body", description: "ID da publicação" },
      { name: "reason", type: "string", required: false, location: "body", description: "Motivo (fica na linha do tempo)" },
    ],
    responseExample: { success: true },
  },
  {
    id: "approve-group-post",
    method: "POST",
    path: "/api/v1/group-posts/approve",
    category: "Grupos",
    title: "Aprovar Texto da IA",
    description: "Aprova o texto gerado pela IA que está aguardando revisão, opcionalmente substituindo-o por uma versão editada.",
    params: [
      { name: "groupPostId", type: "string", required: true, location: "body", description: "ID da publicação" },
      { name: "editedText", type: "string", required: false, location: "body", description: "Publica este texto no lugar do gerado" },
    ],
    responseExample: { success: true },
  },
  {
    id: "reject-group-post",
    method: "POST",
    path: "/api/v1/group-posts/reject",
    category: "Grupos",
    title: "Rejeitar Texto da IA",
    description: "Rejeita o texto gerado pela IA. Nada é publicado naquele horário.",
    params: [
      { name: "groupPostId", type: "string", required: true, location: "body", description: "ID da publicação" },
      { name: "reason", type: "string", required: false, location: "body", description: "Motivo (fica na linha do tempo)" },
    ],
    responseExample: { success: true },
  },
];

export function getEndpoint(id: string): ApiEndpoint | undefined {
  return ALL_ENDPOINTS.find((e) => e.id === id);
}

export function getEndpointsByCategory(category: string): ApiEndpoint[] {
  return ALL_ENDPOINTS.filter((e) => e.category === category);
}
